version: '3.1'

services:
  passport:
    image: ferma666/passport
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - "../:/usr/web/CAS"
    ports:
      - "8003:8000"
